lightsaml_sp.metadata:
    path: /metadata.xml
    defaults: { _controller: LightSaml\SpBundle\Controller\DefaultController::metadata }

lightsaml_sp.discovery:
    path: /discovery
    defaults: { _controller: LightSaml\SpBundle\Controller\DefaultController::discovery }

lightsaml_sp.login:
    path: /login
    defaults: { _controller: LightSaml\SpBundle\Controller\DefaultController::login }

lightsaml_sp.login_check:
    path: /login_check

lightsaml_sp.sessions:
    path: /sessions
    defaults: { _controller: LightSaml\SpBundle\Controller\DefaultController::sessions }
